name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
     id-token: write
     contents: read

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
            - name: Inspect GitHub OIDC claims
        shell: bash
        run: |
          RESPONSE=$(curl -sS \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com")

          TOKEN=$(echo "$RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin)['value'])")

          PAYLOAD=$(echo "$TOKEN" | cut -d '.' -f2)

          python3 - "$PAYLOAD" <<'PY'
          import sys, json, base64

          payload = sys.argv[1]
          payload += "=" * (-len(payload) % 4)

          claims = json.loads(base64.urlsafe_b64decode(payload))

          print("aud =", claims.get("aud"))
          print("sub =", claims.get("sub"))
          print("repository =", claims.get("repository"))
          print("repository_id =", claims.get("repository_id"))
          print("repository_owner =", claims.get("repository_owner"))
          print("repository_owner_id =", claims.get("repository_owner_id"))
          print("ref =", claims.get("ref"))
          PY
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::325502190209:role/terraform-shipping-lab-github-terraform
          aws-region: af-south-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate